### ISSUE TITLE
LittleTiles rendering issue

### ISSUE THREAD

**Issue by CreativeMD** [Chisel-2/Chisel-2#311]
Hello,
i'm the author of LittleTiles (https://github.com/CreativeMD/LittleTiles). There is an issue with chisel microblocks, they all rendering as a solid block, so maybe you could change some parts in your code.

I saw that your RenderBlocksCTM.java class does ignore the bounds. I would be really really happy if you could change it to vanilla caculations :D.

BTW connected textures are working fine that is really really nice :D

**Comment by Drullkus** [comment]
"They all rendering as a solid block"

Confused by this :S

**Comment by CreativeMD** [comment]
http://i.imgur.com/EjPFvDx.png
http://i.imgur.com/vTjSr1E.png
http://i.imgur.com/4saL3q1.png

and i also noticed that this is the wrong icon :D maybe we can fix this as well.

**Comment by tterrag1098** [comment]
@CreativeMD Could you please try this with the latest [dev build](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/)? The issue you are referring to was fixed [here](8abc50634bceae8250e3c460e049f60273d6abbf).

**Comment by CreativeMD** [comment]
Nothing has changed using the latest dev build

**Comment by CreativeMD** [comment]
So is there a way to fix this? and could you may show me how i could set the metadata for the icon?

**Comment by CptSpaceToaster** [comment]
I think I'm a dumb... but who's doing the rendering here?

Is this little Tiles code that's rendering one of our blocks, and choking on how we set it up?  Or are we rendering something improperly?  Or is this a Forge Microblocks thing?

**Comment by tterrag1098** [comment]
I think the problem is that RenderBlocksCTM ignores the block bounds,
which is an easy fix. We need to call setRenderBoundsFromBlock.

**Comment by CreativeMD** [comment]
Yes :D , that would be very very cool
and is there a way to manipulate the texture (the metadata), because world.getBlockMetadata(x, y, z) will always return 0.

**Comment by tterrag1098** [comment]
Er...what?

**Comment by CreativeMD** [comment]
Ok,
your renderer renders the factory block with the metadata 0.
http://i.imgur.com/4saL3q1.png
It should be the yellow & black one, my question is:
Is there a way to tell your renderer that it should use a specific metadata instead of checking the blocks metadata?

**Comment by CptSpaceToaster** [comment]
CreativeMD placed down a black and yellow thin-panel, and a factory block with metadata 0, full bounds was drawn instead.

**Comment by CreativeMD** [comment]
yes :D

**Comment by tterrag1098** [comment]
>Is there a way to tell your renderer that it should use a specific metadata instead of checking the blocks metadata?

Is that supported by vanilla?

**Comment by CreativeMD** [comment]
Nope, i'm using my own renderer for this.
So you could do something like this:

public int metadata = -1;

@Override
public IIcon getBlockIcon(Block par1Block, IBlockAccess par2IBlockAccess, int par3, int par4, int par5, int par6)
    {
		if(metadata != -1) return this.getIconSafe(par1Block.getIcon(par6, meta));
        return super.getBlockIcon(par1Block, par2IBlockAccess, par3, par4, par5, par6);
    }

**Comment by tterrag1098** [comment]
@CreativeMD What do you mean? You are using your own RenderBlocks instance? By nature that will be incompatible with chisel rendering.

**Comment by CreativeMD** [comment]
I don't modify the vanilla one, but i create a new own.

**Comment by tterrag1098** [comment]
Right, that's what I mean. Chisel does the same, thus it is incompatible.

**Comment by tterrag1098** [comment]
A way you could get around this is by using a wrapper on the IBlockAccess you pass which returns the "true" metadata value for the block.

**Comment by CreativeMD** [comment]
oh, never heard about that, but i will take a look at it :D thanks

**Comment by tterrag1098** [comment]
@CreativeMD This is how EnderIO manages facade rendering, we pass the block a "fake" IBlockAccess that tells it the metadata it should be.

**Comment by CreativeMD** [comment]
Nice! Thanks,
does this work for tileentities as well?

**Comment by CptSpaceToaster** [comment]
inb4 link to EnderIO source?

**Comment by tterrag1098** [comment]
No, facades do not support TE data, it would be too much work to keep the TE properly updated. Thankfully chisel does not have any decorative blocks that use TEs.

**Comment by CreativeMD** [comment]
Yes :D
so you will change your rendering to support the vanilla bounds?

**Comment by tterrag1098** [comment]
It currently *supports* block bounds, the issue is that it does not take into account the blocks bounds and automatically set them prior to rendering, they must be set manually. I'll try and think up a way to do this well at some point.

**Comment by CreativeMD** [comment]
Sorry if i'm annoying you, but i just wanted to ask when you will add support for block bounds?

**Comment by tterrag1098** [comment]
@CreativeMD That should fix it, let me know when tonight's dev build goes up.

**Comment by CreativeMD** [comment]
Tested it using DEV-2.4.0.110 and nothing changed (still not working). I looked into the code and noticed that some of your renderer don't take the bounds into account: github.com/TheCricket/Chisel-2/blob/master/src/main/java/com/cricketcraft/chisel/client/render/RenderBlocksCTM.java#L178

**Comment by tterrag1098** [comment]
That's the wrong code branch, you want dev.

**Comment by CreativeMD** [comment]
oh, but it still somehow ignores the bounds
